name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Upload
        run: |
          tar -cvpzf upload.tar.gz * .htaccess
          curl -F 'file=@upload.tar.gz' -F 'p=${{ secrets.UPLOAD_PASSWORD }}' https://api.javacakegames.com/upload.php
